framework:
    messenger:
        buses:
            messenger.bus.default:
                middleware:
                    - App\Middleware\OrderMiddleware

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            'App\Message\OrderMessage': async
            'App\Message\OrderProcessedMessage': async
